# Generated by Django 2.2 on 2020-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200811_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_country_area',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_country_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_first_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_last_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='captured_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer_ip_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fraud_message',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fraud_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='message',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='token',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
    ]
