# Generated by Django 2.2 on 2020-08-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200811_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
