# Generated by Django 2.2 on 2020-08-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
