# Generated by Django 2.2 on 2020-08-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200812_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Cart'),
        ),
    ]
