# Generated by Django 2.2 on 2020-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('isVeg', models.BooleanField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
