# Generated by Django 2.2 on 2020-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200809_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
    ]
