# Generated by Django 2.2 on 2020-08-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_cart_items'),
        ('food', '0003_auto_20200809_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Cart'),
        ),
    ]
