# Generated by Django 2.2 on 2020-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
