# Generated by Django 2.2 on 2020-08-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200810_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Cart'),
        ),
    ]
